language: node_js
sudo: required
dist: trusty
addons:
  browserstack:
    username: williamhill2
    access_key:
      secure: GXG1OWR0a1qgv6tQmUD2BQkk+ABZU7MwqlqEofNdWkdRQVWPv7YBkjnz7mQ+97IkohHndXtpyD22po6gQsdPmck+dYWf2SO0GTgIL3qzaCLTIZCtdek5DHFv8cOLHiu2SvCjAGg6E5RkuMzEYts4N/WLZHdAknahy/9HcB2dvtW77sZZzTG3EaxXrcEaLPMUfp33cKDN0FG3uYbx3w+rcENf427W5HZ6FhqWJ4GUd5WV+/Hv5pkeRNC5XQ5xZbgi1vbAscnyYJ235zRb1EZ/T9XJ5ejQWg7lhNgdxRfJ4Yj8wcNsB2BxYIOFkpm/AHMrK1j0i/8OfS6GkRVBsIU2LHkOXb1jLYKTcNLQWlu5wCRjTL1LE3ZWcyOyLFTzgkX2julReOJMidOLfv3QPOx1sjDxUdWSoAydXxnrkob7QkhU2Mh+sOEQ4E2OinLV5KfMXAqMki+XX+JXtIGc9tcc7tm01ZWOhaMhXV83yME2tB62k6+ve3Oaqg0XdTa/iyVqqlrYOrXA1Z5/OgLHeABAtlPdU4liDGGWJf53+F1fMbT+qY+M6Yd3UKVGvZl6x4RLXU9yDsyXkMsovE4M3vbWRa9q85A5j73Ncs7C6YjRhNMA1waJs45c86nSkyMN3EdcQYDNwgZPjnUznSVMrdHxMqL9hz4Gab+Dy36VKVoMaao=
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
node_js:
- node
- '6'
install:
- npm install
- npm install -g polymer-cli
- polymer install
before_script:
- npm run lint
script:
- xvfb-run npm run test
- xvfb-run npm run test:integration
deploy:
  name: swarm_city_deploy_bot 
  local_dir: build/production
  provider: pages
  skip_cleanup: true
  github_token: J3Or7PYCaMWzyvHHejeoezHiJqPkU51iTQ2oLN8gI+ZS3JF8mRwDCZtYfBmj7NoPhxKyylS5LIS/0tsmsIgI/zjPwz2t8c9P3pUI/O6a1kEtNea2O9Cpx6VpYXS3G1X6eE6rHbhc0WE6WDsv+SgvI//nAvQdDxFtXDXEAXG7fYV97sfPUBGyJ+PhAYQig0T8I9c5l7w/MOm5c2B1DAedTiMuGIhLbDTVnbk+BLqw/ecxZakYKPBCQcoAPkgQxUnmUQPXRthririZKnxyXfVHY5Lqp6ZFWo5jvPRlT8li2bUqTUak6rcFiBd1VGBJl8VsRP3kmEsl4tEGU5MfHPFo+QjCo8vMvoFTSaKKrMy9UAbcnHeq90bo8+COaO29bGsfU1ZmLmE7dJJXz0smtX4m+rID9Oj3R4ntUNUE/yGk9raZVbAqSSE9kRpTnRYY70V3JBfIf83tHPPHk6jT/7vjg1D3aUUt4uUf/8s9iwGgbCvMRgnng9zOZ4WI/Ldz3wuH8IJSofnlE3rz2JXZGk8N2Ww4LCp5cfRqJTj0vicuVj6Or4oPI1KuVX6qUDgDoWZWbrqpqrQe4jze9JdCNsOkGjG/q4j3On8HL/FXxu8VLMRzQ5FnqRPxsIQvmObFJatLCSBusx+i+eDtw1eEQ6GZTjrgNkQE46npSSZtsOXaMTc=
  on:
    branch: master
