version: '2'
services:
  polymer:
    build:
      context: .
      dockerfile: docker/Dockerfile.customelement
    ports:
      - "8081:8081"
  contracts:
    build:
      context: .
      dockerfile: docker/Dockerfile.contracts
  lint:
    build:
      context: .
      dockerfile: docker/Dockerfile.lint
